"""SonicG1: 29-DOF Unitree G1 (legs, 3-DOF waist, 7-DOF arms) + Dex3 grippers,
driven by the external SONIC C++ whole-body controller (over DDS) via the
SonicWholeBodyController composite controller, or by standard controllers.

Assets generated by robosuite/scripts/build_sonic_g1_assets.py (split from SONIC's
validated 29-DOF model; physics identical to the integrated model)."""
import numpy as np
from robosuite.models.robots.manipulators.legged_manipulator_model import LeggedManipulatorModel
from robosuite.utils.mjcf_utils import xml_path_completion

# NOTE: the SonicG1 -> LeggedRobot control-class mapping is registered in
# robosuite/robots/__init__.py ROBOT_CLASS_MAPPING (the hardcoded path used by the
# built-in robots), not via @register_robot_class -- that decorator imports
# robosuite.robots, which would create a circular import here (this module is
# imported from within robosuite.models.robots). The RobotModel itself auto-registers
# in REGISTERED_ROBOTS via its metaclass on class definition.


class SonicG1(LeggedManipulatorModel):
    """29-DOF G1 with a free (un-actuated) floating base; bimanual Dex3 grippers."""

    arms = ["right", "left"]

    def __init__(self, idn=0):
        super().__init__(xml_path_completion("robots/sonic_g1/robot.xml"), idn=idn)

    @property
    def default_base(self):
        # NullBase (add_null_base) leaves the robot's worldbody untouched, so the
        # pelvis's top-level <freejoint/> survives -> a true free-floating 6-DOF base
        # (needed: SONIC's policy controls a floating humanoid; squat/jump/walk move
        # the base in z/pitch/roll, which robosuite's planar FloatingLeggedBase and the
        # freejoint-dropping NoActuationBase/add_mobile_base cannot represent). base_pos
        # reads root_body (the pelvis) directly (robot.py), so no base body is needed.
        # The FIXED variant overrides this (it has no freejoint to preserve).
        return "NullBase"

    @property
    def default_gripper(self):
        return {"right": "SonicDex3RightGripper", "left": "SonicDex3LeftGripper"}

    @property
    def default_controller_config(self):
        return {"right": "default_sonic_g1", "left": "default_sonic_g1"}

    @property
    def init_qpos(self):
        return np.zeros(29)

    @property
    def base_xpos_offset(self):
        return {
            "bins": (-0.5, -0.1, 0.0),
            "empty": (-0.29, 0, 0.0),
            "table": lambda table_length: (-0.26 - table_length / 2, 0, 0.0),
        }

    @property
    def top_offset(self):
        return np.array((0, 0, 1.0))

    @property
    def _horizontal_radius(self):
        return 0.5

    @property
    def arm_type(self):
        return "bimanual"

    @property
    def _eef_name(self):
        return {"right": "right_eef", "left": "left_eef"}

    @staticmethod
    def _right_first(names):
        # robosuite splits the arm joint/actuator lists evenly per side with the FIRST
        # half -> "right" (robot.py _load_arm_controllers / fixed_base_robot.py:96). Our
        # MOTOR_ORDER lists the LEFT arm first, so reorder both arm_joints AND
        # arm_actuators right-first here. Both MUST use the same order: the "right"
        # part controller takes joint_indexes from arm_joints[:split] and writes its
        # torque to arm_actuators[:split] -- if only one is reordered, left/right
        # swap (right-arm torque lands on left-arm actuators). This is a pure relabel
        # for robosuite's part split; it does NOT touch the model's actuator order, so
        # SONIC's own ctrl_idx mapping (built from joint names) is unaffected.
        right = [n for n in names if any(k in n for k in ("r_shoulder", "r_elbow", "r_wrist"))]
        left = [n for n in names if any(k in n for k in ("l_shoulder", "l_elbow", "l_wrist"))]
        return right + left

    @property
    def arm_joints(self):
        return self._right_first(super().arm_joints)

    @property
    def arm_actuators(self):
        return self._right_first(super().arm_actuators)


class SonicG1Fixed(SonicG1):
    """SonicG1 with the floating base removed (pelvis welded). Non-free-floating
    version for manipulation envs -- avoids the FloatingLeggedBase machinery and the
    freejoint-as-arm misclassification. Legs/waist/arms remain actuated (SONIC or
    OSC can drive them)."""

    def __init__(self, idn=0):
        super().__init__(idn=idn)
        self._remove_free_joint()

    @property
    def default_base(self):
        # Fixed variant has no freejoint to preserve; NoActuationBase provides a base
        # body + welds the pelvis -> fixed stance (used by the manipulation/OSC tests).
        return "NoActuationBase"
