name: 잡무(Chore)
description: src나 tests 파일을 바꾸지 않는 일들
title: "[Chore] "
labels: ["🧹 chore"]
body:
- type: textarea
  attributes:
    label: 설명
    description: 무엇을, 왜 변경했는지 설명해주세요. 만약 code를 바꾸는 경우에는 반드시 다른 issue 타입을 사용해주세요.
    placeholder: |
      1. ...를 변경하였고, ...를 추가하였습니다.
      2. 이 작업은 ...를 위한 작업입니다.
      3. ...
  validations:
    required: true
- type: textarea
  attributes:
    label: 제약 사항
    description: 이 이슈를 해결 할 때 제약 사항을 적어 주세요, 그 제약 사항을 지키면서 이슈를 해결해야 합니다.
    placeholder: |
      1. ... 파일은 수정을 하지 말아야 합니다.
      2. 특정 확장자만 파일을 추가해야 합니다.
      3. ...
  validations:
    required: false
